#!/bin/bash

# First, rustup automatically installs the toolchain
# if not installed (by reading ./rust-toolchain).
# Then cargo (re)builds creusot and creusot-contracts.
# TODO: Better way, without executing all the tests.
cargo test
