#!/bin/bash

pushd $(dirname $1) > /dev/null
INPUTPATH=$(pwd)/$(basename $1)
popd > /dev/null
SCRIPTPATH=$(dirname "$BASH_SOURCE")
pushd $SCRIPTPATH > /dev/null
rustc -Cpanic=abort \
  --extern creusot_contracts=./target/debug/libcreusot_contracts.rlib \
  -Ldependency=./target/debug/deps/ \
  $INPUTPATH
popd > /dev/null
