#!/bin/zsh

# First, rustup automatically installs the toolchain
# if not installed (by reading ./rust-toolchain).
# Then cargo (re)builds creusot and creusot-contracts.
# TODO: Better way, without executing all the tests.
SCRIPTPATH=$(dirname "$BASH_SOURCE")
pushd $SCRIPTPATH > /dev/null
rustfmt **/*.rs
popd > /dev/null
