#!/usr/bin/env bash

set -e
SCRIPTPATH=$(dirname "$BASH_SOURCE")
pushd $SCRIPTPATH > /dev/null
for i in "$@" ; do
  case $1 in
    --help)
      echo "Usage: ./fmt [--all] [ARGS]"
      echo "    All other [ARGS] are forwarded to rustfmt; see below"
      echo "Option:"
      echo "    --all   Fmt all .rs files (default is to fmt files with changes from origin/master)"
      echo
      rustfmt --help
      exit 0
      ;;
    --all)
      ARGS=$(git ls-files '*.rs')
      NO_DEFAULT_FILES=1
      shift
      ;;
    -*)
      ARGS+=" $i"
      shift
      ;;
    *)
      ARGS+=" $i"
      NO_DEFAULT_FILES=1
      shift
      ;;
  esac
done
if [ ! "$NO_DEFAULT_FILES" ] ; then
  FILES=$(git diff --name-only origin/master '*.rs')
  [ "$FILES" ] || exit 0
fi
rustfmt $ARGS $FILES
popd > /dev/null
