#!/usr/bin/env bash

SCRIPTPATH=$(dirname "$BASH_SOURCE")
eval $(cargo run --bin dev-env)
why3 \
  --warn-off=unused_variable --warn-off=clone_not_abstract --warn-off=axiom_abstract \
  --debug=coma_no_trivial \
  ide -L "$SCRIPTPATH" $@
