#!/usr/bin/env bash

pushd $(dirname $1) > /dev/null
INPUTPATH=$(pwd)/$(basename $1)
popd > /dev/null
SCRIPTPATH=$(dirname "$BASH_SOURCE")
pushd $SCRIPTPATH > /dev/null
eval $(cargo run --bin dev-env)
PROC=(./target/creusot/debug/build/creusot-std-proc/*/out)
cargo run --bin creusot-rustc --  \
  --edition=2024 \
  -Zno-codegen \
  -Zmacro-backtrace \
  --extern creusot_std=./target/creusot/debug/libcreusot_std.rlib \
  -Ldependency=$PROC \
  --crate-type=lib \
  -Zunpretty=mir \
  -Zdump-mir= \
  "$INPUTPATH" \
  -- \
  --output-file /dev/null \
  --span-mode=absolute \
  --creusot-extern creusot_std=./target/creusot/debug/libcreusot_std.cmeta

popd > /dev/null
