#!/usr/bin/env bash

pushd $(dirname $1) > /dev/null
INPUTPATH=$(pwd)/$(basename $1)
OUTDIR=$(pwd)
popd > /dev/null
SCRIPTPATH=$(dirname "$BASH_SOURCE")
pushd $SCRIPTPATH > /dev/null
eval $(cargo run --bin dev-env)
cargo run --bin creusot-rustc --  \
  --why3-config-file $WHY3CONFIG \
  --output-file="${INPUTPATH%.*}.coma" \
  --span-mode=absolute \
  -- -Zno-codegen \
  -Zmacro-backtrace \
  --extern creusot_contracts=./target/debug/libcreusot_contracts.rlib \
  -Ldependency=./target/debug/deps/ \
  --crate-type=lib \
  $INPUTPATH
popd > /dev/null
