#!/bin/bash

SCRIPTPATH=$(dirname "$0")
cargo run --bin creusot-rustc -- -Zno-codegen \
  --extern creusot_contracts=$SCRIPTPATH/target/debug/libcreusot_contracts.rlib \
  -Ldependency=$SCRIPTPATH/target/debug/deps/ \
  $@
