[prover]
name = "Alt-Ergo"
version = "2.6.2"
command = "alt-ergo --timelimit %.t %f"
driver = "alt_ergo_26"

[prover]
name = "Z3"
version = "4.15.3"
command = "z3 -smt2 -T:%t sat.random_seed=42 nlsat.randomize=false smt.random_seed=42 -st %f"
driver = "z3_4_12"

[prover]
name = "CVC5"
version = "1.3.1"
command = "cvc5 --stats-internal --tlimit=%T %f"
driver = "cvc5"

[prover]
name = "CVC4"
version = "1.8"
command = "cvc4 --stats --tlimit=%T --lang=smt2 %f"
driver = "cvc4_17"

[strategy]
code = "start:
c Alt-Ergo 1. 1000
c Z3 1. 1000
c CVC5 1. 1000
c CVC4 1. 1000
"
desc = "Automatic@ run@ of@ main@ provers"
name = "Auto_level_0"
shortcut = "0"

[strategy]
code = "start:
c Alt-Ergo 5. 1000 | Z3 5. 1000 | CVC5 5. 1000 | CVC4 5. 1000
"
desc = "Automatic@ run@ of@ main@ provers for longer times"
name = "Auto_level_1"
shortcut = "1"

[strategy]
code = "start:
c Alt-Ergo 1. 1000
c Z3 1. 1000
c CVC5 1. 1000
c CVC4 1. 1000
t split_vc start
c Alt-Ergo 10. 1000 | Z3 10. 1000 | CVC5 10. 1000 | CVC4 10. 1000
"
desc = "Automatic@ run@ of@ main@ provers and splitting"
name = "Auto_level_2"
shortcut = "2"

[strategy]
code = "start:
c Alt-Ergo 1. 1000
c Z3 1. 1000
c CVC5 1. 1000
c CVC4 1. 1000
t split_vc start
t introduce_premises afterintro
afterintro:
t inline_goal afterinline
g trylongertime
afterinline:
t split_all_full start
trylongertime:
c Alt-Ergo 30. 1000 | Z3 30. 1000 | CVC5 30. 1000 | CVC4 30. 1000
"
desc = "Automatic@ run@ of@ provers@ and@ most@ useful@ transformations"
name = "Auto_level_3"
shortcut = "3"

[strategy]
code = "start:
c Alt-Ergo .2 1000
c Z3 .2 1000
c CVC5 .2 1000
c CVC4 .2 1000
c Alt-Ergo 1 1000 | Z3 1 1000 | CVC5 1 1000 | CVC4 1 1000
t compute_specified start
t split_vc start
c Alt-Ergo 2 4000 | Z3 2 4000 | CVC5 2 4000 | CVC4 2 4000
"
desc = "Default@ Creusot-Why3find@ strategy"
name = "Creusot_Auto"
shortcut = "4"
