FROM debian:buster-slim

USER root

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -yq && \
		apt-get upgrade -yq --auto-remove && \
		apt-get install -yq curl why3 build-essential

ADD rust-toolchain .
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- -y --default-toolchain $(cat rust-toolchain) && \
    $HOME/.cargo/bin/rustup component add rustc-dev rust-src llvm-tools-preview
ENV PATH=/root/.cargo/bin:$PATH
