name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build-guide:
    runs-on: ubuntu-latest
    environment: deploy guide
    steps:
      - name: Trigger guide deploy
        run: |
          curl --fail-with-body -L -XPOST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GUIDE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/creusot-rs/guide/dispatches \
            -d '{"event_type":"deploy-guide"}'

  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/cache/restore@v5
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'prelude-generator/**') }}
    - name: Install Creusot
      run: |
        ./INSTALL --skip-why3 --skip-why3-conf --skip-prelude --skip-extra-tools
    - name: Build doc
      run: |
        BUILDDIR=ci/build-docs
        cargo creusot doc -- -p creusot-std --no-deps --target-dir $BUILDDIR
        cp ci/html/highlight.css guide/theme/highlight.js $BUILDDIR/doc
      env:
        RUSTDOCFLAGS: '--html-after-content ci/html/postscript.html --html-in-header ci/html/header.html'
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: 'ci/build-docs/doc'

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
